import("../../webrtc.gni")

config("libwebsockets_config") {
}

rtc_library("libwebsockets") {
  defines = [
    # lws_config_private.h
    "LWS_HAVE_DLFCN_H",
    "LWS_HAVE_FCNTL_H",
    "LWS_HAVE_FORK",
    "LWS_HAVE_GETENV",
    "LWS_HAVE_INTTYPES_H",
    "LWS_HAVE_TLS",
    "LWS_HAVE_MALLOC",
    "LWS_HAVE_MEMORY_H",
    "LWS_HAVE_MEMSET",
    "LWS_HAVE_NETINET_IN_H",
    "LWS_HAVE_REALLOC",
    "LWS_HAVE_SOCKET",
    "LWS_HAVE_STDINT_H",
    "LWS_HAVE_STDLIB_H",
    "LWS_HAVE_STRERROR",
    "LWS_HAVE_STRINGS_H",
    "LWS_HAVE_STRING_H",
    "LWS_HAVE_SYS_SOCKET_H",
    "LWS_HAVE_SYS_STAT_H",
    "LWS_HAVE_SYS_TYPES_H",
    "LWS_HAVE_SYS_RESOURCE_H",
    "LWS_HAVE_UNISTD_H",
    "LWS_HAVE_VFORK",
    "LWS_HAVE_WORKING_FORK",
    "LWS_HAVE_WORKING_VFORK",
    "LWS_HAVE_RTA_PREF",
    "LWS_HAVE_HMAC_CTX_new",
      
    # lws_config.h
    "LWS_WITH_CUSTOM_HEADERS",
    "LWS_WITH_BORINGSSL",
    "LWS_WITH_DIR",
    "LWS_WITH_FILE_OPS",
    "LWS_WITH_HTTP_BASIC_AUTH",
    "LWS_WITH_HTTP_UNCOMMON_HEADERS",
    "LWS_WITH_NETWORK",
    "LWS_WITH_CLIENT",
    "LWS_WITHOUT_SERVER",
    "LWS_WITH_CONMON",
#    "LWS_WITH_SYS_ASYNC_DNS",
    "LWS_WITHOUT_EXTENSIONS",
    "LWS_WITH_POLL",
    "LWS_WITH_SYS_STATE",
    "LWS_WITH_TLS",
#    "LWS_WITH_UDP",
#    "LWS_WITH_UNIX_SOCK",
    "LWS_ROLE_RAW_PROXY",
    "LWS_ROLE_RAW_FILE",
    "LWS_ROLE_H1",
    "LWS_ROLE_WS",
    "LWS_PLAT_UNIX",
    "LWS_LOGS_TIMESTAMP",
    "LWS_CLIENT_HTTP_PROXYING",
    "LWS_LIBRARY_VERSION=\"4.3.0\"",
    "LWS_LIBRARY_VERSION_MAJOR=4",
    "LWS_LIBRARY_VERSION_MINOR=3",
    "LWS_LIBRARY_VERSION_PATCH=0",
    "LWS_LIBRARY_VERSION_NUMBER=(LWS_LIBRARY_VERSION_MAJOR*1000000)+(LWS_LIBRARY_VERSION_MINOR*1000)+LWS_LIBRARY_VERSION_PATCH",
    "LWS_LOGGING_BITFIELD_SET=(LLL_ERR|LLL_WARN|LLL_NOTICE|LLL_INFO)",
    "LWS_LOG_TAG_LIFECYCLE=0",
    "LWS_OPENSSL_SUPPORT",
    "LWS_OPENSSL_CLIENT_CERTS=\"/system/etc/security/cacerts\"",
    "LWS_NO_DAEMONIZE",
    "LWS_IPV6",
    "LWS_WITH_IPV6",
    "LWS_MAX_SMP=1",
    "LWS_HAVE_OPENSSL_ECDH_H",
    "LWS_HAVE_PTHREAD_H",
    "LWS_HAVE_RSA_SET0_KEY",
    "LWS_HAVE_SSL_CTX_get0_certificate",
    "LWS_HAVE_SSL_CTX_set1_param",
    "LWS_HAVE_SSL_EXTRA_CHAIN_CERTS",
    "LWS_HAVE_SSL_get0_alpn_selected",
    "LWS_HAVE_SSL_CTX_EVP_PKEY_new_raw_private_key",
    "LWS_HAVE_SSL_set_alpn_protos",
    "LWS_HAVE_SSL_SET_INFO_CALLBACK",
    "LWS_HAVE_TLS_CLIENT_METHOD",
    "LWS_HAVE_TLSV1_2_CLIENT_METHOD",
    "LWS_HAVE_X509_get_key_usage",
    "LWS_HAVE_X509_VERIFY_PARAM_set1_host",
    "LWS_SSL_CLIENT_USE_OS_CA_CERTS",
    "LWS_HAVE_STDINT_H",
    "LWS_HAVE_ATOLL",
    "LWS_HAVE_TLS_CLIENT_METHOD",
    "LWS_HAS_INTPTR_T",
  ]
  
  include_dirs = [
    "lib",
    "include",
    "lib/core",
    "lib/core-net",
    "lib/roles",
    "lib/roles/h1",
    "lib/roles/http",
    "lib/roles/raw-proxy",
    "lib/roles/ws",
    "lib/plat/unix",
    "lib/tls",
    "lib/event-libs",
    "lib/system/metrics",
    "lib/twinlife",
    #"$java_home/include",
    #"$java_home/include/linux",
  ]
    
  sources = [
    "lib/twinlife/wscontainer.cc",
    "lib/plat/unix/unix-caps.c",
    "lib/plat/unix/unix-misc.c",
    "lib/plat/unix/unix-init.c",
    "lib/plat/unix/unix-file.c",
    "lib/plat/unix/unix-pipe.c",
    "lib/plat/unix/unix-resolv.c",
    "lib/plat/unix/unix-service.c",
    "lib/plat/unix/unix-sockets.c",
    "lib/plat/unix/unix-fds.c",
    "lib/tls/tls.c",    
    "lib/tls/tls-network.c",
    "lib/tls/openssl/openssl-tls.c",
    "lib/tls/openssl/openssl-x509.c",
    "lib/tls/openssl/openssl-ssl.c",
    "lib/tls/tls-client.c",
    "lib/tls/openssl/openssl-client.c",    
    "lib/core/alloc.c",
    "lib/core/buflist.c",
    "lib/core/context.c",
    "lib/core/lws_dll2.c",
    "lib/core/libwebsockets.c",
    "lib/core/logs.c",
    "lib/core/vfs.c",
    "lib/misc/base64-decode.c",
    "lib/misc/lws-ring.c",
    "lib/misc/dir.c",
    "lib/misc/lwsac/lwsac.c",
    "lib/misc/lwsac/cached-file.c",
    "lib/misc/sha-1.c",
    "lib/misc/lejp.c",
    "lib/system/system.c",
    "lib/core-net/dummy-callback.c",
    "lib/core-net/output.c",
    "lib/core-net/close.c",
    "lib/core-net/network.c",
    "lib/core-net/vhost.c",
    "lib/core-net/pollfd.c",
    "lib/core-net/service.c",
    "lib/core-net/sorted-usec-list.c",
    "lib/core-net/wsi.c",
    "lib/core-net/wsi-timeout.c",
    "lib/core-net/adopt.c",
    "lib/roles/pipe/ops-pipe.c",
    "lib/core-net/state.c",
    "lib/roles/http/header.c",
    "lib/roles/http/parsers.c",
    "lib/roles/h1/ops-h1.c",
    "lib/roles/ws/client-ws.c",
    "lib/roles/ws/client-parser-ws.c",
    "lib/roles/ws/ops-ws.c",
    # "lib/roles/ws/server-ws.c",
    # "lib/tls/tls-server.c",
    # "lib/tls/openssl/openssl-server.c",
    "lib/roles/raw-skt/ops-raw-skt.c",
    "lib/roles/raw-file/ops-raw-file.c",
    "lib/roles/raw-proxy/ops-raw-proxy.c",
    "lib/roles/listen/ops-listen.c",
    "lib/roles/http/client/client-http.c",
    "lib/roles/http/server/server-http.c",
    "lib/event-libs/poll/poll.c",   
    "lib/core-net/client/client.c",
    "lib/core-net/client/conmon.c",
    "lib/core-net/client/connect.c",
    "lib/core-net/client/connect2.c",
    "lib/core-net/client/connect3.c",
    "lib/core-net/client/connect4.c",
    "lib/core-net/client/sort-dns.c",

# Async DNS (main branch only and produces some crash)
#    "lib/roles/http/date.c",
#    "lib/core-net/route.c",
#    "lib/core-net/client/connect.c",
#    "lib/core-net/client/connect2.c",
#    "lib/core-net/client/connect3.c",
#    "lib/core-net/client/connect4.c",
#    "lib/core-net/client/sort-dns.c",
#    "lib/system/async-dns/async-dns.c",
#    "lib/system/async-dns/async-dns-parse.c",
]
 if (is_ios) {
    sources += [
      "lib/twinlife/TLWebSocket.mm",
    ]
    defines += [
      "LWS_DETECTED_PLAT_IOS",
    ]
 }
 if (is_android) {
    sources += [
      "jni/container_jni.cc",
      "jni/jni_helpers.cc",
      "jni/observer_jni.cc",
      "lib/misc/getifaddrs.c",
      "lib/core-net/route.c",
      "lib/roles/netlink/ops-netlink.c",
    ]
    defines += [
      "LWS_BUILTIN_GETIFADDRS",
      "LWS_HAVE_SYS_PRCTL_H",
      "LWS_WITH_NETLINK",
      "LWS_HAVE_PIPE2",
      "LWS_HAVE_EVENTFD",
    ]
 }
 if (is_linux) {
    # Same as Android but without getifaddrs
    sources += [
      "jni/container_jni.cc",
      "jni/jni_helpers.cc",
      "jni/observer_jni.cc",
      "lib/core-net/route.c",
      "lib/roles/netlink/ops-netlink.c",
    ]
    defines += [
      "LWS_HAVE_SYS_PRCTL_H",
      "LWS_WITH_NETLINK",
      "LWS_HAVE_PIPE2",
      "LWS_HAVE_EVENTFD",
    ]
    include_dirs += [
      "$java_home/include",
      "$java_home/include/linux",
    ]
 }
 deps = [
    "//third_party/boringssl",
    "//rtc_base:ssl"
  ]
}

